[package]
name = "giftwrap"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shell-words = "1.1"
sha1 = "0.10"

[dev-dependencies]
tempfile = "3"
